services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: technatura_db
    ports:
      - "3306:3306"

volumes:
  db_data:
